[package]
name = "qoi-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = "2.0.1"
png = "0.17.6"
log = "0.4.17"
colors-transform = "0.2.11"
